<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class School extends Admin_Controller {
/*
| -----------------------------------------------------
| PRODUCT NAME: 	INILABS SCHOOL MANAGEMENT SYSTEM
| -----------------------------------------------------
| AUTHOR:			INILABS TEAM
| -----------------------------------------------------
| EMAIL:			info@inilabs.net
| -----------------------------------------------------
| COPYRIGHT:		RESERVED BY INILABS IT
| -----------------------------------------------------
| WEBSITE:			http://inilabs.net
| -----------------------------------------------------
*/
	function __construct() {
		parent::__construct();
		$this->load->model("school_m");
		$this->load->model("systemadmin_m");
		$this->load->model("user_m");
		$this->load->model("payment_gateway_option_m");
		$language = $this->session->userdata('lang');
		$this->lang->load('school', $language);
	}

	public function select() {
		if($_POST) {
			$schoolID = $this->input->post("schoolID");

			$siteInfo = $this->site_m->get_site($schoolID);
			$session = [
					"schoolID" => $schoolID,
					"defaultschoolyearID" => $siteInfo->school_year,
					"lang" => $siteInfo->language
			];
			$this->data["siteinfos"] = $siteInfo;
			$this->session->set_userdata($session);
			$this->session->unset_userdata('get_permission');
			$this->session->unset_userdata('dbMenus');
			redirect(base_url('dashboard/index'));
		} else {
			$this->load->library('pagination');
			$user = $this->user_m->get_user_info($this->session->userdata('usertypeID'), $this->session->userdata('loginuserID'));
			$schoolIDs = explode(",", $user->schoolID);

			$config['base_url'] = base_url('school/select');
			$config['total_rows'] = $this->school_m->count_school_wherein($schoolIDs);
			$config['per_page'] = 20;
			$config['num_links'] = 5;
			$config['full_tag_open'] = '<ul class="pagination">';
			$config['full_tag_close'] = '</ul>';
			$config['first_link'] = 'First';
			$config['first_tag_open'] = '<li>';
			$config['first_tag_close'] = '</li>';
			$config['last_link'] = 'Last';
			$config['last_tag_open'] = '<li>';
			$config['last_tag_close'] = '</li>';
			$config['next_link'] = '&gt;';
			$config['next_tag_open'] = '<li>';
			$config['next_tag_close'] = '</li>';
			$config['prev_link'] = '&lt;';
			$config['prev_tag_open'] = '<li>';
			$config['prev_tag_close'] = '</li>';
			$config['cur_tag_open'] = '<li class="active"><a href="#">';
			$config['cur_tag_close'] = '</a></li>';
			$config['num_tag_open'] = '<li>';
			$config['num_tag_close'] = '</li>';

			$this->pagination->initialize($config);

			$page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;
			$this->data['schools'] = $this->school_m->get_school_wherein($schoolIDs, $config['per_page'], $page);
			$this->data['pagination'] = $this->pagination->create_links();

			$this->data["subview"] = "school/select";
			$this->load->view('_layout_select', $this->data);
		}
	}

	public function index() {
		$user = $this->user_m->get_user_info($this->session->userdata('usertypeID'), $this->session->userdata('loginuserID'));
		$this->data['schools'] = $this->school_m->get_order_by_school(array('schoolID !=' => 0));
		$this->data["subview"] = "school/index";
		$this->load->view('_layout_main', $this->data);
	}

	protected function rules() {
		$rules = array(
			array(
				'field' => 'name',
				'label' => $this->lang->line("school_name"),
				'rules' => 'trim|required|xss_clean|max_length[60]'
			),
		);
		return $rules;
	}

	public function add() {
		if($_POST) {
			$rules = $this->rules();
			$this->form_validation->set_rules($rules);
			if ($this->form_validation->run() == FALSE) {
				$this->data["subview"] = "school/add";
				$this->load->view('_layout_main', $this->data);
			} else {
				$array = [];
				$array['name'] = $this->input->post("name");
				$array["create_date"] = date("Y-m-d h:i:s");

				$this->school_m->insert_school($array);
				$id = $this->db->insert_id();

				$array_schoolyear = [
						'schooltype'      => 'classbase',
						'schoolyear'      => ( date('Y') . '-' . ( (int) date('Y') + 1 ) ),
						'startingdate'    => ( date('Y') . '-' . '01-01' ),
						'endingdate'      => ( date('Y') . '-' . '12-31' ),
						"create_date"     => date("Y-m-d h:i:s"),
						"modify_date"     => date("Y-m-d h:i:s"),
						"create_userID"   => $this->session->userdata('loginuserID'),
						"create_username" => $this->session->userdata('username'),
						"create_usertype" => $this->session->userdata('usertype'),
						'schoolID'        => $id,
				];

				$this->schoolyear_m->insert_schoolyear($array_schoolyear);
				$schoolyearID = $this->db->insert_id();

				$array = [
						'attendance'            => 'day',
						'automation'            => 5,
						'auto_invoice_generate' => 0,
						'backend_theme'         => 'default',
						'currency_code'         => 'KES',
						'currency_symbol'       => 'KSH',
						'frontendorbackend'     => true,
						'frontend_theme'        => 'default',
						//'footer'               => 'Copyright &copy; ' . $this->input->post("name"),
						'google_analytics'      => '',
						'language'              => 'english',
						'mark_1'                => 1,
						'note'                  => 1,
						'photo'                 => 'site.png',
						//'purchase_code'         => ( isset($purchaseFileRead['purchase_code']) ? $purchaseFileRead['purchase_code'] : '' ),
						//'purchase_username'     => ( isset($purchaseFileRead['username']) ? $purchaseFileRead['username'] : '' ),
						'school_type'           => 'classbase',
						'school_year'           => $schoolyearID,
						'sname'                 => $this->input->post("name"),
						'student_ID_format'     => 1,
						//'updateversion'         => config_item('ini_version'),
						'captcha_status'        => 1,
						'recaptcha_site_key'    => '',
						'recaptcha_secret_key'  => '',
				];

				$array_permission_relationships = [
					['permission_id' => 501, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 502, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 506, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 507, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 511, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 512, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 516, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 531, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 535, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 536, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 537, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 538, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 539, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 540, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 541, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 542, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 543, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 544, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 548, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 549, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 550, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 551, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 553, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 554, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 556, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 561, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 562, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 563, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 569, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 570, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 571, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 572, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 573, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 579, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 580, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 581, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 582, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 586, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 587, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 588, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 590, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 591, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 592, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 594, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 595, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 596, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 598, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 599, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 600, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 601, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 603, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 604, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 605, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 607, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 683, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 684, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 685, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 686, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 687, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 688, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 693, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 694, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 695, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 713, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 717, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 718, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 721, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 731, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 765, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 766, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 767, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 770, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 771, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 772, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 775, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 776, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 777, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 780, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 781, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 782, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 783, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 787, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 788, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 789, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 790, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 791, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 793, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 794, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 821, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 501, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 512, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 516, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 531, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 539, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 543, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 544, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 548, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 561, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 571, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 573, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 579, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 580, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 687, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 709, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 713, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 716, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 717, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 721, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 722, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 731, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 748, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 752, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 765, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 769, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 770, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 774, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 775, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 779, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 535, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 697, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 501, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 512, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 516, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 554, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 556, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 579, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 580, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 608, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 609, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 610, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 611, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 612, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 613, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 614, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 615, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 616, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 617, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 618, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 619, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 620, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 621, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 622, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 649, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 650, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 651, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 652, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 653, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 654, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 655, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 656, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 657, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 658, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 659, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 660, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 661, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 662, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 663, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 664, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 665, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 666, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 667, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 668, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 669, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 670, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 671, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 672, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 673, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 674, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 675, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 676, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 677, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 678, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 683, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 684, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 685, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 686, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 687, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 688, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 689, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 690, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 691, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 722, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 723, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 724, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 725, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 726, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 727, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 728, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 729, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 730, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 731, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 732, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 733, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 734, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 735, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 736, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 737, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 738, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 739, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 740, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 741, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 742, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 743, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 744, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 745, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 746, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 747, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 748, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 749, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 752, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 753, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 754, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 756, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 757, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 758, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 760, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 761, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 762, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 765, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 769, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 770, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 774, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 775, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 779, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 801, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 802, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 803, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 804, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 805, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 806, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 551, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 553, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 623, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 624, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 625, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 626, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 697, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 704, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 705, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 706, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 707, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 708, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 764, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 807, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 808, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 809, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 810, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 811, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 812, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 878, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 879, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 880, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 881, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 882, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 883, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 884, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 885, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 886, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 887, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 888, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 889, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 890, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 891, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 892, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 893, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 501, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 512, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 516, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 531, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 554, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 556, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 579, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 580, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 687, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 688, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 689, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 704, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 705, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 706, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 707, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 708, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 709, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 710, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 711, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 712, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 713, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 714, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 715, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 716, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 717, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 718, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 719, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 720, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 721, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 765, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 769, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 770, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 774, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 775, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 779, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 788, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 789, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 790, 'usertype_id' => 6, 'schoolID' => $id],
					['permission_id' => 501, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 502, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 506, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 507, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 511, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 512, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 516, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 517, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 521, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 548, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 550, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 551, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 553, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 554, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 556, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 579, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 580, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 687, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 688, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 689, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 765, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 769, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 770, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 774, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 775, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 779, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 814, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 815, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 816, 'usertype_id' => 7, 'schoolID' => $id],
					['permission_id' => 910, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 910, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 911, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 914, 'usertype_id' => 3, 'schoolID' => $id],
					['permission_id' => 914, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 919, 'usertype_id' => 5, 'schoolID' => $id],
					['permission_id' => 502, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 503, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 504, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 505, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 506, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 507, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 508, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 509, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 510, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 511, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 512, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 513, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 514, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 515, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 516, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 517, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 518, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 519, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 520, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 521, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 522, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 523, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 524, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 525, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 526, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 527, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 528, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 530, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 531, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 532, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 533, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 534, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 535, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 536, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 537, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 538, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 539, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 540, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 541, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 542, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 543, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 544, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 545, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 546, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 547, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 548, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 549, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 550, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 551, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 552, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 553, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 554, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 555, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 556, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 557, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 558, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 559, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 560, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 561, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 562, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 563, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 564, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 565, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 566, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 567, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 568, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 569, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 570, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 571, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 572, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 573, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 574, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 575, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 576, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 577, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 578, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 579, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 580, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 581, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 582, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 583, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 584, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 585, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 586, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 587, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 588, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 589, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 590, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 591, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 592, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 593, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 594, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 595, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 596, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 597, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 598, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 599, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 600, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 601, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 602, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 603, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 604, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 605, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 606, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 607, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 608, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 609, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 610, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 611, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 612, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 613, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 614, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 615, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 616, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 617, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 618, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 619, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 620, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 621, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 622, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 623, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 624, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 625, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 626, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 627, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 628, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 629, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 630, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 631, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 632, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 633, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 634, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 635, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 636, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 637, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 638, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 639, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 640, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 641, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 642, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 643, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 644, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 645, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 646, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 647, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 648, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 649, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 650, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 651, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 652, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 653, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 654, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 655, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 656, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 657, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 658, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 659, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 660, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 661, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 662, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 663, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 664, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 665, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 666, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 667, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 668, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 669, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 670, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 671, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 672, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 673, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 674, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 675, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 676, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 677, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 678, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 679, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 680, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 681, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 682, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 683, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 684, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 685, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 686, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 687, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 688, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 689, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 690, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 691, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 692, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 693, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 694, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 695, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 696, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 697, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 698, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 699, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 700, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 701, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 702, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 703, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 704, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 705, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 706, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 707, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 708, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 709, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 710, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 711, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 712, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 713, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 714, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 715, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 716, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 717, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 718, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 719, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 720, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 721, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 722, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 723, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 724, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 725, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 726, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 727, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 728, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 729, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 730, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 731, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 732, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 733, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 734, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 735, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 736, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 737, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 738, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 739, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 740, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 741, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 742, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 743, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 744, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 745, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 746, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 747, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 748, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 749, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 750, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 752, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 753, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 754, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 909, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 756, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 757, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 758, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 759, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 760, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 761, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 762, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 763, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 764, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 765, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 766, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 767, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 768, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 769, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 770, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 771, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 772, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 773, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 774, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 775, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 776, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 777, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 778, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 779, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 780, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 781, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 782, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 783, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 784, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 785, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 786, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 787, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 788, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 789, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 790, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 791, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 792, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 793, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 794, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 795, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 796, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 797, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 798, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 799, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 800, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 801, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 802, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 803, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 804, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 805, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 806, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 807, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 808, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 809, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 810, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 811, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 812, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 813, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 814, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 815, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 816, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 817, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 818, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 819, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 820, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 821, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 822, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 823, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 824, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 825, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 826, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 827, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 828, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 829, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 830, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 831, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 832, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 833, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 834, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 835, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 836, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 837, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 838, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 839, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 840, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 845, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 846, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 847, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 848, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 849, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 850, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 852, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 853, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 854, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 855, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 856, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 872, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 874, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 875, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 876, 'usertype_id' => 0, 'schoolID' => $id],
					['permission_id' => 877, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 878, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 879, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 880, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 881, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 882, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 883, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 884, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 885, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 886, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 887, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 888, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 889, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 890, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 891, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 892, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 893, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 501, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 902, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 899, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 900, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 901, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 905, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 906, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 907, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 908, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 910, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 911, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 912, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 914, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 915, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 916, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 917, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 918, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 919, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 920, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 921, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 922, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 923, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 924, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 925, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 501, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 502, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 506, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 512, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 516, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 531, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 535, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 544, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 548, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 550, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 561, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 571, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 573, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 579, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 580, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 693, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 700, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 709, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 722, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 731, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 765, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 769, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 770, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 774, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 775, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 779, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 599, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 902, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 764, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 797, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 805, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 806, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 807, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 557, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 583, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 585, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 526, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 926, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 927, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 928, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 929, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 930, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 931, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 932, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 933, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 934, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 935, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 936, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 937, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 938, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 939, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 940, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 941, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 941, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 941, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 942, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 943, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 943, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 943, 'usertype_id' => 4, 'schoolID' => $id],
					['permission_id' => 944, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 944, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 945, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 945, 'usertype_id' => 2, 'schoolID' => $id],
					['permission_id' => 954, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 955, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 956, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 957, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 958, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 959, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 960, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 961, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 962, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 963, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 964, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 965, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 966, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 967, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 968, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 969, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 970, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 971, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 972, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 973, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 974, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 975, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 976, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 977, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 978, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 979, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 980, 'usertype_id' => 1, 'schoolID' => $id],
					['permission_id' => 981, 'usertype_id' => 1, 'schoolID' => $id],
				];

				$array_quickbooks_settings_values = [
					['quickbookssettingsID' => 1, 'field_values' => '', 'schoolID' => $id],
					['quickbookssettingsID' => 2, 'field_values' => '', 'schoolID' => $id],
					['quickbookssettingsID' => 3, 'field_values' => '', 'schoolID' => $id],
					['quickbookssettingsID' => 4, 'field_values' => '', 'schoolID' => $id],
					['quickbookssettingsID' => 5, 'field_values' => '', 'schoolID' => $id],
					['quickbookssettingsID' => 6, 'field_values' => '', 'schoolID' => $id],
					['quickbookssettingsID' => 7, 'field_values' => '', 'schoolID' => $id],
					['quickbookssettingsID' => 8, 'field_values' => '', 'schoolID' => $id]
				];

				$array_payment_gateway_option_values = [
					['payment_gateway_option_id' => 1, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 2, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 3, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 4, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 5, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 6, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 7, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 8, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 9, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 10, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 11, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 12, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 13, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 14, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 15, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 16, 'payment_value' => '', 'schoolID' => $id],
					['payment_gateway_option_id' => 17, 'payment_value' => '', 'schoolID' => $id],
				];

				$this->setting_m->insertorupdate($id, $array);
				$this->permission_m->insert_batch_permission_relationships($array_permission_relationships);
				$this->quickbookssettings_m->insert_batch_quickbookssettings_values($array_quickbooks_settings_values);
				$this->payment_gateway_option_m->insert_batch_payment_gateway_option_values($array_payment_gateway_option_values);

				$systemadmin = $this->systemadmin_m->get_systemadmin($this->session->userdata('loginuserID'));
				$schoolID = [];
				if($systemadmin->schoolID != "")
					$schoolID = explode(",", $systemadmin->schoolID);
				$schoolID[] = $id;
				$systemadmins = $this->systemadmin_m->get_order_by_systemadmin(array('schoolID' => $systemadmin->schoolID));
				foreach($systemadmins as $admin) {
					$this->systemadmin_m->update_systemadmin(array('schoolID' => implode(',', $schoolID)), $admin->systemadminID);
				}
				$users = $this->user_m->get_order_by_user(array('schoolID' => $systemadmin->schoolID));
				foreach($users as $user) {
					$this->user_m->update_user(array('schoolID' => implode(',', $schoolID)), $user->userID);
				}
				$systemadmin = $this->systemadmin_m->update_systemadmin(array('schoolID' => implode(',', $schoolID)), $this->session->userdata('loginuserID'));

				$this->session->set_flashdata('success', $this->lang->line('menu_success'));

				$siteInfo = $this->site_m->get_site($id);
				$session = [
						"schoolID" => $id,
						"defaultschoolyearID" => $siteInfo->school_year,
						"lang" => $siteInfo->language
				];
				$this->data["siteinfos"] = $siteInfo;

				$this->session->set_userdata($session);
				redirect(base_url("school/index"));
			}
		} else {
			$this->data["subview"] = "school/add";
			$this->load->view('_layout_main', $this->data);
		}
	}

	public function edit() {
		$id = htmlentities(escapeString($this->uri->segment(3)));
		if((int)$id) {
			$user = $this->user_m->get_user_info($this->session->userdata('usertypeID'), $this->session->userdata('loginuserID'));
			$this->data['school'] = $this->school_m->get_school($id);
			if($this->data['school'] && in_array($id, explode(',', $user->schoolID))) {
				if($_POST) {
					$rules = $this->rules();
					$this->form_validation->set_rules($rules);
					if ($this->form_validation->run() == FALSE) {
						$this->data["subview"] = "school/edit";
						$this->load->view('_layout_main', $this->data);
					} else {
						$array = [];
						$array['name'] = $this->input->post("name");

						$this->school_m->update_school($array, $id);
						$this->session->set_flashdata('success', $this->lang->line('menu_success'));
						redirect(base_url("school/index"));
					}
				} else {
					$this->data["subview"] = "school/edit";
					$this->load->view('_layout_main', $this->data);
				}
			}
		} else {
			$this->data["subview"] = "error";
			$this->load->view('_layout_main', $this->data);
		}
	}

	public function unique_school() {
		$id = htmlentities(escapeString($this->uri->segment(3)));
		if((int)$id) {
			$schools = $this->school_m->get_order_by_school(array("name" => $this->input->post("name"), "schoolID !=" => $id));
			if(customCompute($schools)) {
				$this->form_validation->set_message("unique_school", "%s already exists");
				return FALSE;
			}
			return TRUE;
		} else {
			$schools = $this->school_m->get_order_by_school(array("name" => $this->input->post("name")));
			if(customCompute($schools)) {
				$this->form_validation->set_message("unique_school", "%s already exists");
				return FALSE;
			}
			return TRUE;
		}
	}
}
