#!/bin/bash
# Rollback Script
# Generated by Master Orchestration Agent
# Execution Time: < 2 minutes

set -e

BACKUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$(dirname "$BACKUP_DIR")")"

echo "Starting rollback from backup: $BACKUP_DIR"
echo "Target directory: $ROOT_DIR"

# Extract codebase backup
echo "Restoring codebase..."
cd "$ROOT_DIR"
tar -xzf "$BACKUP_DIR/codebase.tar.gz"

# Restore configuration
echo "Restoring configuration..."
cp -r "$BACKUP_DIR/config/.env" "$ROOT_DIR/.env" 2>/dev/null || true
cp -r "$BACKUP_DIR/config/Config/"* "$ROOT_DIR/app/Config/" 2>/dev/null || true

# Clear caches
echo "Clearing caches..."
php spark cache:clear

echo "Rollback complete!"
echo "Duration: $(date)"