<?php

declare(strict_types=1);

namespace Modules\Orchestration\Reports;

use Modules\Orchestration\Config\OrchestrationConfig;

/**
 * Report Generator.
 *
 * Generates HTML and JSON reports for orchestration results
 *
 * @version 1.0.0
 */
class ReportGenerator
{
    protected OrchestrationConfig $config;

    public function __construct(OrchestrationConfig $config)
    {
        $this->config = $config;
    }

    /**
     * Generate orchestration summary report.
     */
    public function generateOrchestrationReport(array $results, string $outputDir): string
    {
        $htmlFile = "{$outputDir}/orchestration-report.html";

        $html = $this->generateReportHtml($results);
        file_put_contents($htmlFile, $html);

        return $htmlFile;
    }

    /**
     * Generate HTML report.
     */
    protected function generateReportHtml(array $results): string
    {
        $runId = $results['run_id'] ?? 'unknown';
        $success = $results['success'] ? 'SUCCESS' : 'FAILED';
        $statusClass = $results['success'] ? 'success' : 'error';
        $duration = $results['duration'] ?? 0;

        $phasesHtml = '';
        foreach ($results['phases'] ?? [] as $phase) {
            $phaseStatus = $phase['success'] ? '✅' : '❌';
            $phasesHtml .= '<tr>';
            $phasesHtml .= "<td>{$phaseStatus}</td>";
            $phasesHtml .= "<td>Phase {$phase['number']}</td>";
            $phasesHtml .= "<td>{$phase['name']}</td>";
            $phasesHtml .= "<td>{$phase['duration']}s</td>";
            $phasesHtml .= '<td>' . ($phase['success'] ? 'Success' : 'Failed') . '</td>';
            $phasesHtml .= '</tr>';
        }

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Orchestration Report - {$runId}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif; margin: 0; padding: 20px; background: #f0f2f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        h1 { color: #1a1a1a; border-bottom: 3px solid #007bff; padding-bottom: 15px; margin-bottom: 30px; }
        .status-badge { display: inline-block; padding: 8px 16px; border-radius: 4px; font-weight: bold; }
        .status-badge.success { background: #d4edda; color: #155724; }
        .status-badge.error { background: #f8d7da; color: #721c24; }
        .meta-info { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin: 30px 0; }
        .meta-card { background: #f8f9fa; padding: 20px; border-radius: 6px; border-left: 4px solid #007bff; }
        .meta-card h3 { margin: 0 0 10px 0; color: #495057; font-size: 14px; text-transform: uppercase; }
        .meta-card .value { font-size: 24px; font-weight: bold; color: #212529; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #dee2e6; }
        th { background: #007bff; color: white; font-weight: 600; }
        tr:hover { background: #f8f9fa; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #dee2e6; color: #6c757d; text-align: center; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🎯 Master Orchestration Report</h1>
        
        <div class="status-badge {$statusClass}">{$success}</div>
        
        <div class="meta-info">
            <div class="meta-card">
                <h3>Run ID</h3>
                <div class="value">{$runId}</div>
            </div>
            <div class="meta-card">
                <h3>Duration</h3>
                <div class="value">{$duration}s</div>
            </div>
            <div class="meta-card">
                <h3>Timestamp</h3>
                <div class="value">{$results['start_time']}</div>
            </div>
        </div>
        
        <h2>📊 Phase Execution Summary</h2>
        <table>
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Phase</th>
                    <th>Name</th>
                    <th>Duration</th>
                    <th>Result</th>
                </tr>
            </thead>
            <tbody>
                {$phasesHtml}
            </tbody>
        </table>
        
        <div class="footer">
            <p>Generated by Master Orchestration Agent v1.0.0</p>
            <p>ShuleLabs CI4 - School Management System</p>
        </div>
    </div>
</body>
</html>
HTML;
    }
}
