#!/usr/bin/env bash
set -euo pipefail

banner() {
    local message="$*"
    local timestamp
    timestamp="$(date '+%Y-%m-%d %H:%M:%S')"
    printf '\n\033[1;34m[%s] %s\033[0m\n' "$timestamp" "$message"
}

require_command() {
    local cmd="$1"
    if ! command -v -- "$cmd" >/dev/null 2>&1; then
        echo "Error: Required command '$cmd' is not available." >&2
        exit 1
    fi
}

PHP_BIN="${PHP_BIN:-php}"
require_command "$PHP_BIN"
require_command sed
require_command grep
require_command find
require_command xargs

APP_ROOT="${APP_ROOT:-${1:-/var/www/besha}}"
ENV_FILE="$APP_ROOT/.env"
LOG_DIR="$APP_ROOT/application/logs"

if [ ! -d "$APP_ROOT" ]; then
    echo "Error: APP_ROOT directory '$APP_ROOT' does not exist." >&2
    exit 1
fi

cd "$APP_ROOT"
export APP_ROOT

if [ ! -f "$ENV_FILE" ]; then
    banner "Creating missing .env file at ${ENV_FILE}"
    mkdir -p "$(dirname "$ENV_FILE")"
    : >"$ENV_FILE"
fi

backup_file="${ENV_FILE}.bak-menu-visibility"
if [ ! -f "$backup_file" ]; then
    banner "Creating .env backup at ${backup_file}"
    cp "$ENV_FILE" "$backup_file"
fi

ensure_trailing_newline() {
    local file="$1"

    if [ ! -s "$file" ]; then
        return
    fi

    local last_char
    last_char=$(tail -c1 "$file" 2>/dev/null) || last_char=''
    if [ "$last_char" != $'\n' ]; then
        printf '\n' >>"$file"
    fi
}

update_env_flag() {
    local key="$1"
    local value="$2"

    if grep -qE "^${key}=" "$ENV_FILE"; then
        sed -i "s/^${key}=.*/${key}=${value}/" "$ENV_FILE"
    else
        ensure_trailing_newline "$ENV_FILE"
        printf '%s=%s\n' "$key" "$value" >>"$ENV_FILE"
    fi
}

banner "Phase 3 – Enable menu visibility feature flags"
update_env_flag FLAG_OKR_V1 true
update_env_flag FLAG_CFR_V1 true
update_env_flag FLAG_UNIFIED_STATEMENT true
update_env_flag FLAG_PAYROLL_V2 true
update_env_flag FLAG_PERMISSIONS_V1 true

banner "Phase 4 – Re-seed admin menu overrides"
"$PHP_BIN" index.php migrate version 20240701000030

banner "Phase 4.5 – Run menu_overrides seeder"
"$PHP_BIN" index.php migrate/seed menu_overrides

banner "Phase 5 – Validate required controllers and views"
required_files=(
    "mvc/controllers/Cfr.php"
    "mvc/controllers/FinanceStatement.php"
    "mvc/controllers/Payroll.php"
    "mvc/views/cfr/index.php"
    "mvc/views/finance/statement_index.php"
    "mvc/views/payroll/index_v2.php"
)

create_placeholder() {
    local file="$1"
    local type="$2"

    mkdir -p "$(dirname "$file")"

    if [ "$type" = "controller" ]; then
        local class_name
        class_name="$(basename "$file" .php)"
        cat >"$file" <<PHP
<?php

/**
 * Placeholder controller generated by scripts/menu_visibility_patch.sh.
 */

defined('BASEPATH') || exit('No direct script access allowed.');

class ${class_name} extends CI_Controller
{
    public function index()
    {
        show_error('This controller is a placeholder generated by the automation script.');
    }
}
PHP
    else
        cat >"$file" <<'PHP'
<?php
/**
 * Placeholder view generated by scripts/menu_visibility_patch.sh.
 */
PHP
    fi
}

for file in "${required_files[@]}"; do
    if [ ! -f "$file" ]; then
        banner "Creating missing file ${file}"
        case "$file" in
            mvc/controllers/*)
                create_placeholder "$file" controller || {
                    echo "Error: Failed to create placeholder for ${file}." >&2
                    exit 1
                }
                ;;
            *)
                create_placeholder "$file" view || {
                    echo "Error: Failed to create placeholder for ${file}." >&2
                    exit 1
                }
                ;;
        esac
    fi
done

banner "Phase 6 – Run targeted July 2nd migration"
"$PHP_BIN" index.php migrate version 20240702090000

banner "Phase 7 – Bring migrations current"
"$PHP_BIN" index.php migrate latest
"$PHP_BIN" index.php migrate/status

banner "Phase 7.5 – Run PHP lint sweep"
find mvc application -type f -name '*.php' -print0 | xargs -0 -r -n1 "$PHP_BIN" -l

banner "Phase 8 – Clear cached menu entries from ci_sessions"
"$PHP_BIN" <<'PHP'
<?php

$stderrHandle = null;

if (defined('STDERR')) {
    $nativeStderr = constant('STDERR');
    if (is_resource($nativeStderr)) {
        $stderrHandle = $nativeStderr;
    }
}

if (!is_resource($stderrHandle)) {
    $handle = @fopen('php://stderr', 'wb');
    if ($handle === false) {
        $handle = @fopen('php://output', 'wb');
    }

    if ($handle !== false) {
        $stderrHandle = $handle;
    }
}

$closeOnShutdown = false;
if (is_resource($stderrHandle)) {
    if (defined('STDERR')) {
        $nativeStderr = constant('STDERR');
        if (is_resource($nativeStderr) && $stderrHandle === $nativeStderr) {
            $closeOnShutdown = false;
        } else {
            $closeOnShutdown = true;
        }
    } else {
        $closeOnShutdown = true;
    }
}

if ($closeOnShutdown) {
    register_shutdown_function(static function () use ($stderrHandle) {
        if (is_resource($stderrHandle)) {
            fclose($stderrHandle);
        }
    });
}

function warn($message)
{
    global $stderrHandle;

    $line = "Warning: $message\n";

    if (is_resource($stderrHandle)) {
        fwrite($stderrHandle, $line);
    } else {
        echo $line;
    }
}

$appRoot = getenv('APP_ROOT');
if (!$appRoot) {
    warn('APP_ROOT is not defined.');
    exit(1);
}

$envConfig = $appRoot . '/mvc/config/env.php';
$databaseConfig = $appRoot . '/mvc/config/database.php';

if (!is_file($envConfig)) {
    warn("Unable to locate env configuration at {$envConfig}.");
    exit(1);
}

if (!is_file($databaseConfig)) {
    warn("Unable to locate database configuration at {$databaseConfig}.");
    exit(1);
}

if (!extension_loaded('mysqli')) {
    warn('The mysqli PHP extension is required but not loaded.');
    exit(1);
}

if (!defined('BASEPATH')) {
    $systemPath = rtrim($appRoot . '/system', DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;
    define('BASEPATH', $systemPath);
}

require_once $envConfig;
require $databaseConfig;

if (!isset($db['default']) || !is_array($db['default'])) {
    warn('Database configuration for the default connection is not available.');
    exit(1);
}

$config = $db['default'];

$hostname = $config['hostname'] ?? '';
$username = $config['username'] ?? '';
$password = $config['password'] ?? '';
$database = $config['database'] ?? '';
$driver = $config['dbdriver'] ?? 'mysqli';
$port = $config['port'] ?? null;
$prefix = $config['dbprefix'] ?? '';
$allowEmptyPassword = false;
if (array_key_exists('allow_empty_password', $config)) {
    $allowEmptyPassword = (bool) $config['allow_empty_password'];
} else {
    $envAllow = getenv('DB_ALLOW_EMPTY_PASSWORD');
    if ($envAllow !== false) {
        $filtered = filter_var($envAllow, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
        $allowEmptyPassword = $filtered === null ? false : $filtered;
    }
}

if (strtolower($driver) !== 'mysqli') {
    warn("Unsupported database driver '{$driver}'. Only mysqli is supported for this automation.");
    exit(1);
}

$missing = [];
foreach (['hostname' => $hostname, 'username' => $username, 'database' => $database] as $field => $value) {
    if (trim((string) $value) === '') {
        $missing[] = $field;
    }
}

if (trim((string) $password) === '' && !$allowEmptyPassword) {
    $missing[] = 'password';
}

if (!empty($missing)) {
    warn('Database credentials are incomplete: ' . implode(', ', $missing));
    exit(1);
}

mysqli_report(MYSQLI_REPORT_OFF);
$mysqli = mysqli_init();
if ($mysqli === false) {
    warn('Failed to initialize MySQLi extension.');
    exit(1);
}

$connected = false;
if ($port) {
    $connected = $mysqli->real_connect($hostname, $username, $password, $database, (int) $port);
} else {
    $connected = $mysqli->real_connect($hostname, $username, $password, $database);
}

if (!$connected) {
    warn('Database connection failed: ' . $mysqli->connect_error);
    exit(1);
}

$table = $prefix . 'ci_sessions';
$tableEscaped = str_replace('`', '``', $table);

$tableCheckSql = 'SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? LIMIT 1';
$tableCheck = $mysqli->prepare($tableCheckSql);
if ($tableCheck === false) {
    warn('Failed to prepare table existence check: ' . $mysqli->error);
    $mysqli->close();
    exit(1);
}

if (!$tableCheck->bind_param('ss', $database, $table)) {
    warn('Failed to bind table existence parameters: ' . $tableCheck->error);
    $tableCheck->close();
    $mysqli->close();
    exit(1);
}

if (!$tableCheck->execute()) {
    warn('Failed to execute table existence check: ' . $tableCheck->error);
    $tableCheck->close();
    $mysqli->close();
    exit(1);
}

if ($tableCheck->store_result() === false) {
    warn('Failed to buffer table existence result: ' . $tableCheck->error);
    $tableCheck->close();
    $mysqli->close();
    exit(1);
}

$tableExists = $tableCheck->num_rows > 0;
$tableCheck->close();

if (!$tableExists) {
    echo "Table '{$table}' does not exist. No sessions to clear." . PHP_EOL;
    $mysqli->close();
    exit(0);
}

$stmt = $mysqli->prepare(sprintf('DELETE FROM `%s` WHERE `data` LIKE ?', $tableEscaped));
if ($stmt === false) {
    warn('Failed to prepare deletion statement: ' . $mysqli->error);
    $mysqli->close();
    exit(1);
}

$needle = '%dbMenus%';
if (!$stmt->bind_param('s', $needle)) {
    warn('Failed to bind deletion parameter: ' . $stmt->error);
    $stmt->close();
    $mysqli->close();
    exit(1);
}

if (!$stmt->execute()) {
    warn('Failed to execute deletion statement: ' . $stmt->error);
    $stmt->close();
    $mysqli->close();
    exit(1);
}

$deleted = $stmt->affected_rows;
$stmt->close();
$mysqli->close();

echo "Cleared {$deleted} session row(s) containing dbMenus." . PHP_EOL;
PHP

banner "Phase 8.8 – Run menu visibility smoke test"
set +e
"$PHP_BIN" scripts/smoke_menu_visibility.php
smoke_status=$?
set -e
if [ $smoke_status -ne 0 ]; then
    echo "Smoke test exited with status ${smoke_status}. Continuing." >&2
fi

banner "Phase 9 – Review recent application logs"
if [ -d "$LOG_DIR" ]; then
    latest_log="$(find "$LOG_DIR" -type f -name 'log-*.php' -printf '%T@ %p\n' | sort -nr | head -n1 | cut -d' ' -f2- || true)"
    if [ -n "$latest_log" ]; then
        echo "Displaying tail of $latest_log"
        tail -n 50 "$latest_log"
    else
        echo "No log-*.php files found in $LOG_DIR."
    fi
else
    echo "Log directory '$LOG_DIR' does not exist."
fi

banner "Sprint automation completed"
