<?php

declare(strict_types=1);

namespace Modules\Finance\Controllers\Api;

use CodeIgniter\RESTful\ResourceController;
use Modules\Finance\Services\TransactionsService;

/**
 * TransactionsApiController
 * 
 * RESTful API controller for transactions
 * Generated by Master Orchestration Agent
 * 
 * @package Modules\Finance\Controllers\Api
 * @version 1.0.0
 * @generated 2025-11-22
 */
class TransactionsApiController extends ResourceController
{
    protected $modelName = '';
    protected $format = 'json';
    protected TransactionsService $service;

    public function __construct()
    {
        $this->service = new TransactionsService();
    }

    /**
     * List all resources
     */
    public function index(): \CodeIgniter\HTTP\ResponseInterface
    {
        try {
            $page = (int) ($this->request->getGet('page') ?? 1);
            $perPage = (int) ($this->request->getGet('per_page') ?? 20);
            
            $result = $this->service->paginate($page, $perPage);
            
            return $this->respond($result);
        } catch (\Throwable $e) {
            return $this->failServerError($e->getMessage());
        }
    }

    /**
     * Show a specific resource
     */
    public function show($id = null): \CodeIgniter\HTTP\ResponseInterface
    {
        try {
            $resource = $this->service->findById((int) $id);
            
            if (!$resource) {
                return $this->failNotFound('Resource not found');
            }
            
            return $this->respond($resource);
        } catch (\Throwable $e) {
            return $this->failServerError($e->getMessage());
        }
    }

    /**
     * Create a new resource
     */
    public function create(): \CodeIgniter\HTTP\ResponseInterface
    {
        try {
            $data = $this->request->getJSON(true);
            
            $validationErrors = $this->service->validate($data);
            if (!mpty($validationErrors)) {
                return $this->failValidationErrors($validationErrors);
            }
            
            $id = $this->service->create($data);
            
            return $this->respondCreated(['id' => $id]);
        } catch (\Throwable $e) {
            return $this->failServerError($e->getMessage());
        }
    }

    /**
     * Update an existing resource
     */
    public function update($id = null): \CodeIgniter\HTTP\ResponseInterface
    {
        try {
            $data = $this->request->getJSON(true);
            
            $validationErrors = $this->service->validate($data, (int) $id);
            if (!mpty($validationErrors)) {
                return $this->failValidationErrors($validationErrors);
            }
            
            $success = $this->service->update((int) $id, $data);
            
            if (!$success) {
                return $this->failNotFound('Resource not found');
            }
            
            return $this->respondUpdated(['id' => $id]);
        } catch (\Throwable $e) {
            return $this->failServerError($e->getMessage());
        }
    }

    /**
     * Delete a resource
     */
    public function delete($id = null): \CodeIgniter\HTTP\ResponseInterface
    {
        try {
            $success = $this->service->delete((int) $id);
            
            if (!$success) {
                return $this->failNotFound('Resource not found');
            }
            
            return $this->respondDeleted(['id' => $id]);
        } catch (\Throwable $e) {
            return $this->failServerError($e->getMessage());
        }
    }
}
